name: kossumba_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.2
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_map: 4.0.0
  flutter_map_dragmarker: ^4.1.3
  flutter_multi_formatter: ^2.13.8
  flutter_rating: ^2.0.2
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: null
  flutter_slidable: 3.1.2
  font_awesome_flutter: ^10.5.0
  geolocator: 11.1.0
  google_fonts: null
  google_maps_flutter: ^2.1.1
  http: ^0.13.3
  http_parser: ^4.0.2
  image_picker: ^1.0.8
  intl: ^0.19.0
  latlong2: ^0.8.2
  lottie: ^2.7.0
  path: ^1.8.3
  riverpod_annotation: null
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  url_launcher: null

dev_dependencies:
  build_runner: null
  custom_lint: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: 2.3.11

flutter:
  uses-material-design: true
  assets:
    - assets/images/
fonts:
  - family: Poppins
    fonts:
      - asset: fonts/Poppins-Regular.ttf
      - asset: fonts/Poppins-Bold.ttf
        weight: 700
