name: kossumba_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_map: 4.0.0
  flutter_map_dragmarker: ^4.1.3
  flutter_slidable: 3.1.2
  geolocator: 11.1.0
  google_maps_flutter: ^2.1.1
  http: ^0.13.3
  image_picker: ^1.0.8
  intl: ^0.19.0
  latlong2: ^0.8.2
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  url_launcher: null
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
